apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
  namespace: ds
data:
  POSTGRES_DB: dolphinscheduler
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin12345