# permissions for end users to edit dsalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dsalert-editor-role
rules:
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsalerts/status
  verbs:
  - get
