# permissions for end users to view dsalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dsalert-viewer-role
rules:
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsalerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsalerts/status
  verbs:
  - get
