# permissions for end users to edit dsmasters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dsmaster-editor-role
rules:
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsmasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsmasters/status
  verbs:
  - get
