# permissions for end users to view dsworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dsworker-viewer-role
rules:
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsworkers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsworkers/status
  verbs:
  - get
