# permissions for end users to edit dsworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dsworker-editor-role
rules:
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsworkers/status
  verbs:
  - get
