---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsalerts/finalizers
  verbs:
  - update
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsalerts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsapis/finalizers
  verbs:
  - update
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsmasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsmasters/finalizers
  verbs:
  - update
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsmasters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsworkers/finalizers
  verbs:
  - update
- apiGroups:
  - ds.apache.dolphinscheduler.dev
  resources:
  - dsworkers/status
  verbs:
  - get
  - patch
  - update
