apiVersion: ds.apache.dolphinscheduler.dev/v1alpha1
kind: DSApi
metadata:
  name: ds-api
  namespace: ds
  labels:
    app: ds-api
spec:
  replicas: 1
  version: 3.0.0-alpha
  zookeeper_connect: "172.17.0.5:2181"
  repository: apache/dolphinscheduler-api
  datasource:
    drive_name: "org.postgresql.Driver"
    url: "jdbc:postgresql://172.17.0.4:5432/dolphinscheduler"
    username: "postgresadmin"
    password: "admin12345"