kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ds-pv-claim
  labels:
    app: ds-pvc
  namespace: ds
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: pv
