apiVersion: v1
kind: Service
metadata:
  name: ds-alert-service
  namespace: ds
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  selector:
    app: ds-alert




