apiVersion: v1
kind: Service
metadata:
  name: ds-api-service
  namespace: ds
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
      nodePort: 30001
  selector:
    app: ds-api




