apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
  namespace: ds
spec:
  type: NodePort
  #type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30022
      protocol: TCP
  selector:
    app: postgres